Separate launch files
GSO-soslab/alpha_rise_auv pull request #23
Opened 2024-06-05 19:45 UTC by tjsos

2024-06-05 23:08 UTC, mzhouURI requested changes
some minor edits are needed

2024-06-05 23:08 UTC, mzhouURI commented on alpha_rise_bringup/launch/bringup_control.launch
I will call this bringup_mvp.launch, and we should launch mvp_control first.

2024-06-05 23:08 UTC, mzhouURI commented on alpha_rise_bringup/launch/bringup_sensors.launch
can you move dvl to the last? so when I am using this file for bench top test, I can quickly comment dvl out.

2024-06-06 14:55 UTC, tjsos commented
- Changed `bringup_control` to `bringup_mvp` & placed mvp_control first for launch.
- Moved DVL launch statement to the end of `bringup_sensors`

2024-06-06 20:09 UTC, merged